pipeline {
    agent any
    stages {
        stage('build docker image') {
            steps {
                sh 'docker build -t pnotifier_bot:latest .'
            }
        }
        stage('tag and push image') {
            when {
                branch 'main'
            }
            steps {
                sh "docker tag pnotifier_bot:latest ${PRIVATE_DOCKER_REGISTRY}/pnotifier_bot:${GIT_COMMIT}"
                sh "docker push ${PRIVATE_DOCKER_REGISTRY}/pnotifier_bot:${GIT_COMMIT}"
            }
        }
        stage('deploy container stack') {
            when {
                branch 'main'
            }
            steps {
                sh """DOCKER_HOST="ssh://jenkins@${DOCKER_DEPLOY_HOST}:22" \
                    docker-compose up -d"""
            }
        }
    }
}