pipeline {
    agent any
    stages {
        stage('Run tests') {
            steps {
                withPythonEnv('pnotifier_venv') {
                    sh "which python3"
                }
            }
        }
    }
}